spring:
  profiles:
    active: aws, jwt, oauth
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/HAFIT_DB
    password: '001016'

  jpa:
    open-in-view: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

  http:
    encoding:
      charset: UTF-8
      enabled: 'true'
      force: 'true'
  mvc:
    path match:
      matching-strategy: ant_path_matcher # springboot 2.6 이상에서 swagger와 설정이슈