cloud:
  aws:
    credentials:
      accessKey: AKIASTLRGDOBI3WVFT4G
      secretKey: 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
    s3:
      bucket: feedback-file-bucket
    stack:
      auto: 'false'
    region:
      static: ap-northeast-2
spring:
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
