cloud:
  aws:
    credentials:
      accessKey: 
      secretKey: 
    s3:
      bucket: feedback-file-bucket
    stack:
      auto: 'false'
    region:
      static: ap-northeast-2
spring:
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
