spring:
  profiles:
    active: aws, jwt, oauth
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3305/HAFIT_DB
    password: 'root'

  jpa:
    open-in-view: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

  http:
    encoding:
      charset: UTF-8
      enabled: 'true'
      force: 'true'