spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 222404835996-kvfeli2114e5mk5fdnn4staepd8fbrmb.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

          naver:
            client-id: Gk0YyHLoce_xI6hhSLjY
            client-secret: P4WjvIEgiV
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: f889a83d8772a1901d42ecc688a47281
            client-secret: St9YxwnmhkZjMDl0ZzoPdulvAa6aXcE3
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id